name: Verify - ex jdk8

on:
  push:
    branches-ignore:
      - dependabot/**

  pull_request:
    branches:
      - main


jobs:
  build:
    name: Verify
    uses: slawekjaranowski/maven-actions-shared/.github/workflows/maven-verify-with-its.yml@main
    with:
      # exclude jdk8 form all build and maven 3.6.3 with jdk 17
      matrix-exclude: >
        [
          {"jdk": "8"},
          {"mvn": "3.6.3", "jdk": "17"}
        ]
