name: Verify - ex jdk8

on:
  push:
    branches-ignore:
      - dependabot/**

  pull_request:
    branches:
      - main


jobs:
  build:
    name: Verify
    uses: slawekjaranowski/maven-actions-shared/.github/workflows/maven-verify-with-its.yml@main
    with:
      matrix-exclude: '[ {"jdk": "8"} ]'
      matrix-include: '[ {"jdk": "18-ea", "jdk-dist": "zulu"} ]'
