name: Verify

on:
  push:
    branches-ignore:
      - dependabot/**

  pull_request:
    branches:
      - main


jobs:
  build:
    name: Verify
    uses: slawekjaranowski/.github/workflows/maven-verify-with-its.yml@main
