name: Verify

on:
  push:
    branches-ignore:
      - dependabot/**

  pull_request:

jobs:
  build:
    name: Verify
    uses: slawekjaranowski/maven-actions-shared/.github/workflows/maven-verify-with-its.yml@main
